sudo: required

cache: bundler

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
  
language: ruby
# sudo: required
rvm:
# - "1.9.3" # FIXME: this does not work because of 'byebug' which is incompatible with ruby < 2.0
  - "2.0.0"
# - "2.1.0" # FIXME: ruby-2.1.0 does not work because of a problem with bundler compatibility
  - "2.2.2"
  - "2.2.4" # FIXME: this fails under osx
  - "2.3.0" # FIXME: this fails under osx

before_install:
   - ./.travis_before_install.sh

script: 
  - bundle exec rake csound:build
  - bundle exec rake test

#
# this is to integrate gitter
#
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/58e16cc964053ecea477
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
addons:
  code_climate:
    repo_token: c2bdab022fc8be90c1bdd0c735aac395b8b2bd111b06b0f28e08a346e4423485
